version: '3.8'

services:
  db:
    image: "postgres:latest"
    restart: "unless-stopped"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${BANANA_DATABASE_USER}
      POSTGRES_DB: ${BANANA_DATABASE_NAME}
      POSTGRES_PASSWORD: ${BANANA_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
